---
version: "3.6"
services:
  stlib:
    image: ghcr.io/eduardooliveira/stlib:main
    container_name: stlib
    volumes:
      - ./library:/library
      - ./config.toml:/app/config.toml
    ports:
      - 8000:8000
    environment:
      - "THINGIVERSE_TOKEN": "" # needed for the thingiverse download feature
      #- "PORT": 8000
      #- "LIBRARY_PATH": "./library"
      #- "MAX_RENDER_WORKERS": 5
      #- "MODEL_RENDER_COLOR": "#ffffff"
      #- "MODEL_BACKGROUND_COLOR": "#000000"
      #- "LOG_PATH": "./log" # If you wish to log to a file
    
    restart: unless-stopped