port = 8000
library_path = "./testdata"
max_render_workers = 10
file_blacklist = [".potato",".example"]
model_render_color = "#167DF0"
model_background_color =  "#FFFFFF"
#thingiverse_token = "your_thingiverse_token"
#jwt_secret = "" #changemmmeee,changemeee my friend
enable_auth = true
system_path = "./config/system"